### ISSUE TITLE
No results for Charleston rail sources

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#106]
After trying the 5 different source types in Norfolk, I did a test in Charleston just to make sure everything was still good there. All the programs completed successfully, but the rail output doesn't have any records (results_CPORT_RAIL_Output.csv). The railways.csv file has 676 sources listed.

 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409169.88/
TOTALruntime =      3.310 seconds.
 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409169.88/
TOTALruntime =      0.096 seconds.
 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409169.88/
TOTALruntime =      0.422 seconds.
 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409169.88/
TOTALruntime =      1.851 seconds.
 Input Directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1427409169.88/
TOTALruntime =      2.692 seconds.

**Comment by michellegrace** [comment]
This was caused by using the same analytical line solution for roads and rail. There is an "impact factor" computed for roads using the AADT, since the AADT for rails as never defined this "impact" was zero, so nothing was computed. I made a separate rail analytical line routine which does not have this impact factor computation. ... so FIXED!
