### ISSUE TITLE
Emissions displayed beyond the user screen

### ISSUE THREAD

**Issue by michellegrace** [CEMPD/ctools#109]
The emissions for some sources (Point, Rail and Area at least) have emissions displayed beyond the user view (see below). This can be fixed by changing the displayed precision and adding a scroll bar to see columns to the right. Numbers should be displayed in scientific notation (some emissions are pretty small).

![screen shot 2015-03-31 at 1 33 15 pm](https://cloud.githubusercontent.com/assets/10077162/6925001/8e579bc0-d7aa-11e4-85e7-f1ce36b5daa8.png)

**Comment by cseppan** [comment]
I made several changes to help with this problem.

1. For point and underway sources, I split the columns into two tabs. Initially, the "Emissions" tab is selected which displays the emissions values. A second tab labeled "Stack parameters" shows the stack height, diameter, temperature, and velocity columns.

2. I added formatting for the emissions values with a maximum of 4 decimal places. Values less than 0.01 use exponential notation like "3.8051e-5". Special values of -999 and 0 display as-is.

3. I made some tweaks to the page layout so that the content within the box scrolls instead of extending beyond the right edge of the window.

4. I removed "tons/year" from the pollutant column labels and added a note "All emissions values given in tons/year." above the table.
