### ISSUE TITLE
Rail vs All

### ISSUE THREAD

**Issue by arunacs** [CEMPD/ctools#124]
I ran C-PORT for Charleston with all default options, but 6 different times, once each for the 5 source types, and once with all source checked. I was initially testing Catherine's update for receptors for rail source dispersion.Looks like the roads-based receptor algorithm for rail is working. But the ranges of concentrations when comparing rail vs ALL sources do not seem consistent.  The rail-alone dispersion seems to show much higher ranges along the rail-lines than the ALL source version, for the same legend max shown.

Ran ALL, rail at ~8:30 am, and the other 4 sources between noon and 1pm today.

![char_allsrc_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776868/6a96d466-008c-11e5-8575-a0595d9ac384.png)
![char_area_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776869/6aa0aa36-008c-11e5-90d2-4f5f5939b407.png)
![char_point_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776871/6aaf25ac-008c-11e5-8a7a-6738cd844fb9.png)
![char_rail_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776870/6aaa8fba-008c-11e5-9695-e690ee91d187.png)
![char_road_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776873/6ab549b4-008c-11e5-993d-5869bf11294e.png)
![char_shipsintr_winter_nox](https://cloud.githubusercontent.com/assets/10534766/7776872/6ab41c06-008c-11e5-920b-1d57a8186d93.png)

**Comment by joellenb** [comment]
Please specify what source is included in which picture. Thanks!

**Comment by arunacs** [comment]
The sequence of images are:
ALL
Area
Point
Rail
Road
Ships-in-Transit

**Comment by joellenb** [comment]
I tried to get a difference map produced between the ALL sources and just the rail sources. Configured the model runs for Charleston and all default values. Unfortunately, process timed out before completing. (Time out message was appropriately displayed.)

**Comment by michellegrace** [comment]
Jo Ellen,
You know you can get all your run results on nas01??? Even if they time out on the web UI the results are written to nas01

Go here: /nas01/depts/ie/cempd/EPA-RARE/ctools/street2

Based on this comment time your runs are 1432328374.21 and 1432328374.2

You can then find differences between the "ALL" and "Rail".

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by michellegrace** [comment]
Sorry for the long email, please get a cup of coffee and read the ENTIRE thing!……

I looked at what I believe are saran's runs from the output directory:

-rw-r--r--   1 cseppan cep-emc 3221059 May 22 08:28 Char_All_May21_143229746657.tar.gz

-rw-r--r--   1 cseppan cep-emc  708015 May 22 08:30 Char_Rail_May21_143229773712.tar.gz

-rw-r--r--   1 cseppan cep-emc 1331559 May 22 11:56 Char_Rail_May21_143231012844.tar.gz ** this one is mislabeled? actually ROAD **

-rw-r--r--   1 cseppan cep-emc  369189 May 22 11:58 Char_SIT_May21_143231028977.tar.gz

-rw-r--r--   1 cseppan cep-emc  275058 May 22 11:59 Char_Area_May21_143231036974.tar.gz

-rw-r--r--   1 cseppan cep-emc 3221050 May 22 12:05 Char_All_May21_143231048997.tar.gz

-rw-r--r--   1 cseppan cep-emc  410547 May 22 13:00 Char_Point_May21_143231397745.tar.gz


The corresponding files in the street2 directory are:

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 08:28 1432297466.57/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 08:30 1432297737.12/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 11:56 1432310128.44/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 11:58 1432310289.77/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 11:59 1432310369.74/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 12:05 1432310489.97/

drwxr-xr-x   2 cseppan cep-emc  4096 May 22 13:00 1432313977.45/

I looked at the "ALL" run you made at 12:05pm (dir 1432310489.97), here is the head from all results files:

==> 1432310489.97/results.csv <==  *** this is the "TOTAL"… Others are from my dispersion code directly ***

x,y,concentration

1567077.14828,-660628.185445,0.3349781

1567985.06561,-660458.338484,0.3435497

1568892.96452,-660288.393149,0.3521864

1569800.84502,-660118.349441,0.3623642

1570708.70708,-659948.207362,0.3713566

1571616.55071,-659777.966915,0.3851381

1572524.37588,-659607.628101,0.4467169

1573432.18259,-659437.190922,0.6838507

1574339.97083,-659266.65538,1.1136836


==> 1432310489.97/results_CTOOLS_AREA_Output.csv <==

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.000000E+00

 2,  0.156799E+07, -0.660458E+06,  0.000000E+00

 3,  0.156889E+07, -0.660288E+06,  0.000000E+00

 4,  0.156980E+07, -0.660118E+06,  0.000000E+00

 5,  0.157071E+07, -0.659948E+06,  0.000000E+00

 6,  0.157162E+07, -0.659778E+06,  0.000000E+00

 7,  0.157252E+07, -0.659608E+06,  0.000000E+00

 8,  0.157343E+07, -0.659437E+06,  0.000000E+00

 9,  0.157434E+07, -0.659267E+06,  0.000000E+00


==> 1432310489.97/results_CTOOLS_POINT_Output.csv <==

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.302873E+00

 2,  0.156799E+07, -0.660458E+06,  0.311120E+00

 3,  0.156889E+07, -0.660288E+06,  0.319754E+00

 4,  0.156980E+07, -0.660118E+06,  0.328798E+00

 5,  0.157071E+07, -0.659948E+06,  0.338273E+00

 6,  0.157162E+07, -0.659778E+06,  0.348202E+00

 7,  0.157252E+07, -0.659608E+06,  0.358610E+00

 8,  0.157343E+07, -0.659437E+06,  0.370019E+00

 9,  0.157434E+07, -0.659267E+06,  0.377352E+00


==> 1432310489.97/results_CTOOLS_RAIL_Output.csv <==

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.215320E-01

 2,  0.156799E+07, -0.660458E+06,  0.215504E-01

 3,  0.156889E+07, -0.660288E+06,  0.212308E-01

 4,  0.156980E+07, -0.660118E+06,  0.220250E-01

 5,  0.157071E+07, -0.659948E+06,  0.211858E-01

 6,  0.157162E+07, -0.659778E+06,  0.246631E-01

 7,  0.157252E+07, -0.659608E+06,  0.754402E-01

 8,  0.157343E+07, -0.659437E+06,  0.300752E+00

 9,  0.157434E+07, -0.659267E+06,  0.722819E+00


==> 1432310489.97/results_CTOOLS_ROAD_Output.csv <==

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.000000E+00

 2,  0.156799E+07, -0.660458E+06,  0.000000E+00

 3,  0.156889E+07, -0.660288E+06,  0.000000E+00

 4,  0.156980E+07, -0.660118E+06,  0.000000E+00

 5,  0.157071E+07, -0.659948E+06,  0.000000E+00

 6,  0.157162E+07, -0.659778E+06,  0.000000E+00

 7,  0.157252E+07, -0.659608E+06,  0.000000E+00

 8,  0.157343E+07, -0.659437E+06,  0.000000E+00

 9,  0.157434E+07, -0.659267E+06,  0.000000E+00


==> 1432310489.97/results_CTOOLS_SIT_Output.csv <==

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.105731E-01

 2,  0.156799E+07, -0.660458E+06,  0.108793E-01

 3,  0.156889E+07, -0.660288E+06,  0.112016E-01

 4,  0.156980E+07, -0.660118E+06,  0.115412E-01

 5,  0.157071E+07, -0.659948E+06,  0.118978E-01

 6,  0.157162E+07, -0.659778E+06,  0.122730E-01

 7,  0.157252E+07, -0.659608E+06,  0.126667E-01

 8,  0.157343E+07, -0.659437E+06,  0.130797E-01

 9,  0.157434E+07, -0.659267E+06,  0.135126E-01

This tells you nothing about the interpolated image, but from this quick glance the total results.csv file does look like the sum of the 5 parts.

Then I checked the concentrations in the 1432297737.12/ (the RAIL only run)
 [ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ head 1432297737.12/results_CTOOLS_RAIL_Output.csv

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.215320E-01

 2,  0.156799E+07, -0.660458E+06,  0.215504E-01

 3,  0.156889E+07, -0.660288E+06,  0.212308E-01

 4,  0.156980E+07, -0.660118E+06,  0.220250E-01

 5,  0.157071E+07, -0.659948E+06,  0.211858E-01

 6,  0.157162E+07, -0.659778E+06,  0.246631E-01

 7,  0.157252E+07, -0.659608E+06,  0.754402E-01

 8,  0.157343E+07, -0.659437E+06,  0.300752E+00

 9,  0.157434E+07, -0.659267E+06,  0.722819E+00


These results look identical to the RAIL file in the ALL run above.


One complication of comparing the ALL concentration to the RAIL only concentration is that the receptor.csv files are different in both runs.  I think it is due to the transect receptors for the roads, rail, and SIT. ……


To see what is going I did a wc –l on all of these directories:

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432297466.57/receptors.csv

33106 1432297466.57/receptors.csv  ** 8:28 ALL **

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432297737.12/receptors.csv

9581 1432297737.12/receptors.csv ** 8:30 RAIL **

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432310128.44/receptors.csv

21656 1432310128.44/receptors.csv ** 11:56 ROAD **

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $  wc -l 1432310289.77/receptors.csv

6871 1432310289.77/receptors.csv **11:58 SIT**

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432310369.74/receptors.csv

2501 1432310369.74/receptors.csv **11:59 AREA**

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432310489.97/receptors.csv

33106 1432310489.97/receptors.csv **12:05 ALL**

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ wc -l 1432313977.45/receptors.csv

2501 1432313977.45/receptors.csv **13:00 POINT**

Note: there is one header line in each file.


OK, so I think the regular grid is 2500 receptors, then the transect receptors are added when one of the line source types (Road, Rail, or SIT) is computed. This explains the difference in the number of receptors and a lot of different lines when I did a "diff" between the concentration of the rail only run and ALL run receptors.



Then I noticed that there is a "results.csv" in all runs. So I looked at the top of the results and the results_CTOOLS_RAIL files from the Rail only run:

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ head 1432297737.12/results.csv

x,y,concentration

1567077.14828,-660628.185445,0.021532

1567985.06561,-660458.338484,0.0215504

1568892.96452,-660288.393149,0.0212308

1569800.84502,-660118.349441,0.022025

1570708.70708,-659948.207362,0.0211858

1571616.55071,-659777.966915,0.0246631

1572524.37588,-659607.628101,0.0754402

1573432.18259,-659437.190922,0.300752

1574339.97083,-659266.65538,0.722819

[ /nas01/depts/ie/cempd/EPA-RARE/ctools/street2 ] $ head 1432297737.12/results_CTOOLS_RAIL_Output.csv

 RecID, xLCC, yLCC, "NOx_ppb"

 1,  0.156708E+07, -0.660628E+06,  0.215320E-01

 2,  0.156799E+07, -0.660458E+06,  0.215504E-01

 3,  0.156889E+07, -0.660288E+06,  0.212308E-01

 4,  0.156980E+07, -0.660118E+06,  0.220250E-01

 5,  0.157071E+07, -0.659948E+06,  0.211858E-01

 6,  0.157162E+07, -0.659778E+06,  0.246631E-01

 7,  0.157252E+07, -0.659608E+06,  0.754402E-01

 8,  0.157343E+07, -0.659437E+06,  0.300752E+00

 9,  0.157434E+07, -0.659267E+06,  0.722819E+00


These files look like they contain the same concentrations, just a different format.


When Catherine gets back I think that we need to verify the interpolation routine is ALWAYS using the results.csv and I think this issue is NULL and VOID… i.e. I am convinced that the interpolated ALL and RAIL interpolated images are correct, if they are indeed both interpolating the concentrations from the "results.csv" file in both cases.


… I hope you survived all that detective work and extremely detailed presentation of evidence……

At least the NYR won while I was doing this…. GO RANGERS!

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by joellenb** [comment]
The user has to carefully look at the individual legends to see differences. A potential future feature would allow the user to specify the legend to use, thereby making comparisons between scenarios easier.
