### ISSUE TITLE
info box: Your version information goes here.

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#125]
The actual version information needs to be displayed instead of the message:
Your version information goes here.

[i] box on the opening C-PORT screen.
![versioninfogoeshere_05222015](https://cloud.githubusercontent.com/assets/10145737/7779526/30800b1e-00a3-11e5-8eb4-d6819bc457be.PNG)

**Comment by joellenb** [comment]
C-PORT version 1.1 released on June 5, 2015

per Michelle

**Comment by michellegrace** [comment]
I just thought I would add that we should keep the C-LINE and C-PORT versions the same. This is because the dispersion and web interface codes are now the same between these 2 tools. The only difference on the backend is that C-LINE has source types "turned-off", otherwise these are identical tools (and code bases).
