### ISSUE TITLE
CTOOLS_HOURLY ROAD error in Tampa

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#131]
> cd /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/CPORT
> CTOOLS_HOURLY.ifort.x ROAD ../1433177959.42/
 Source type is: ROAD
 Input directory is: ../1433177959.42/
 Source #         158 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         159 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         229 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         230 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         231 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         965 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #         966 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #        1095 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
 Source #        1096 
  changed from rural to urban nfc(due to lack of rural fleet mix in State = 
          12 and County =          103 ).
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 12, file /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/CLINE/MOVES_EFtables/rateperdistance_smoke_20130227a_nei2011v1_20130621_**000_1_TOT.txt
Image              PC                Routine            Line        Source             
CTOOLS_HOURLY.ifo  00000000004A4AFD  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  00000000004A3605  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  000000000044E129  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  000000000041521F  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  0000000000414A52  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  000000000041E4ED  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  00000000004042F1  compute_file_size          20  compute_file_size.f90
CTOOLS_HOURLY.ifo  000000000040DA2E  read_moves_                80  road_read_moves.f90
CTOOLS_HOURLY.ifo  0000000000411035  compute_hourlyemi         163  road_compute_hourlyemissions.f90
CTOOLS_HOURLY.ifo  000000000040FB9F  road_                      51  road.f90
CTOOLS_HOURLY.ifo  0000000000406003  MAIN__                     31  ctools_main.f90
CTOOLS_HOURLY.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          00000030A361ED5D  Unknown               Unknown  Unknown
CTOOLS_HOURLY.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by michellegrace** [comment]
Catherine,
Are you getting this error anywhere else? and the ** in the file name is puzzling... My first 2 guesses are: (1)  the mapping fuel for representative counties could be messed up somewhere;  or (2) the fips state and county codes could be wrong in the database. Can you give me the state and county fips for your run?

Thanks.

-Michelle

**Comment by cseppan** [comment]
Looking at the roads.csv file, the only state and county codes in the run are 12057 and 12103. These both have entries in the MCXREF file:

0,12,57,0,12,86
0,12,103,0,12,86

So I'm not sure why CTOOLS_HOURLY isn't trying to read the 12086 emission factors table.

I did a test over in Gulfport (1433179512.64) where the two counties in the domain are assigned to the representative county 28049. In that case, CTOOLS_HOURLY looked for the correct emission factors table, but ran into a different problem because the file is missing.

forrtl: severe (29): file not found, unit 12, file /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/CLINE/MOVES_EFtables/rateperdistance_smoke_20130227a_nei2011v1_20130621_28049_1_TOT.txt

**Comment by michellegrace** [comment]
I fixed this & updated CURRENT… will add more later.. Have to run now!

-Michelle
------------------------------------------------------------------
Michelle G. Snyder, Environmental Modeler
Institute for the Environment/CEMPD
University of North Carolina at Chapel Hill
Campus Box 1105 (27599-1105)
Europa Center Suite 490 Rm. 4052
100 Europa Dr.
Chapel Hill, NC 27517

phone: 919-843-7561
email: michellesnyder@unc.edu<mailto:michellesnyder@unc.edu>

**Comment by michellegrace** [comment]
Ok all,
I traced this error back to a place where I missed updating the number of temperature bins to 28. Because an array was only defined with 26 temperature dimensions this was writing over space in the memory allocated to other variables, in this case it changes the number of sources to millions instead of 1116. This means when it hit source 1117 it did not have a state of county tips, causing the " _**000_" in the filename. Once I traced this down and correctly allocated 28 temperature bins everything worked correctly.

The Gulfport problem was a different one.... This there was the rateperdistance_smoke_20130227a_nei2011v1_20130621_28049_7_TOT.txt file, but not the January "1" file. So I asked Changsy to go back to his scripts where he combined the rateperdistance for all mobile source processes and there were a few x-connection errors, when he re-ran this last night it added this missing/needed file.

I was in a rush yesterday evening to get something out to you guys, so I just went through my steps and recompiled and committed everything. I wanted to make sure I did everything right and cleaned up all the write statements I needed to add to figure out where the error was coming from (love fortran debugging.. not!). The new code is in MGScode/CTOOLS_6-1-15 and I updated the CURRENT pointer to this directory.

-Michelle
