### ISSUE TITLE
Need to load previous scenario twice to get multipliers back

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#142]
The first time you load a previously saved scenario, it zooms to your domain, shows the correct run parameters in the analysis window (time of day, season, met condition, etc) but does not show the correct modified emission values or AADT/speeds/etc if you had previously used the multipliers to change any of these parameters before saving.

You need to double click the saved scenario again, and only after that does it show the correct emissions, AADT, or speeds.

This happens for all source types (roads, area sources, etc)

**Comment by kdtalgo** [comment]
Update: This occurs only during certain clicking sequences. For example, if you load another saved scenario and then return to the saved scenario in question, the multiplied values show up correct. However if you select a different port using the "Select Your Location" button on the left, do some stuff, and then try to return to the saved scenario, the multiplied values don't appear until you click the scenario twice. Really odd.

**Comment by cseppan** [comment]
The problem was due to the application incorrectly loading fresh data from the server in some cases. If your current map data was locked (like when you had loaded an existing scenario), then when you picked a different scenario, the app would skip trying to load data from the server. If your data was not locked (like after picking a new location), you would get fresh data loaded which would replace the scenario-specific values.

I fixed the problem by making sure that no data is ever loaded from the server whenever you pick an existing scenario.
