### ISSUE TITLE
CTOOLS_ANNUAL bad fleet mix file

### ISSUE THREAD

**Issue by cseppan** [CEMPD/ctools#148]
The CTOOLS_ANNUAL executable tried to open a fleet mix file named 17***_fleet_dist_nei2011.txt. I ran the same set of inputs through CTOOLS_HOURLY (1435039778.24) with no problem.

 Source type is: ROAD
 Input directory is: 
 /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/1435039838.77/
Read inputs runtime =      0.017 seconds.
Dispersion runtime =    497.720 seconds.
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 12, file /nas01/depts/ie/cempd/EPA-RARE/ctools/street2/CLINE/FleetMix_Tables/17***_fleet_dist_nei2011.txt
Image              PC                Routine            Line        Source             
CTOOLS_ANNUAL.ifo  00000000004A70BD  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  00000000004A5BC5  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  00000000004506E9  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  00000000004177DF  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  0000000000417012  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  0000000000420AAD  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  00000000004042F1  compute_file_size          20  compute_file_size.f90
CTOOLS_ANNUAL.ifo  000000000040F45C  read_fleetmix_             38  road_read_fleetmix.f90
CTOOLS_ANNUAL.ifo  0000000000412002  aa_road_                  235  aa_road.f90
CTOOLS_ANNUAL.ifo  0000000000406144  MAIN__                     31  aa_ctools_main.f90
CTOOLS_ANNUAL.ifo  000000000040330C  Unknown               Unknown  Unknown
libc.so.6          0000003EDE21ED5D  Unknown               Unknown  Unknown
CTOOLS_ANNUAL.ifo  0000000000403219  Unknown               Unknown  Unknown

**Comment by michellegrace** [comment]
I found that this was due to a memory leak/overwrite. I went through and checked that all variables that were allocated the status was checked. I also found that some variable, especially fleet mix, was allocated multiple times because a roadways would have different representative counties, so I made sure to check that variables within a loop that could be allocated multiple times are first deallocated (if allocated) and I checked this status also. This is fixed in the latest release version data 06/25/15.
