### ISSUE TITLE
Changing name of scenario

### ISSUE THREAD

**Issue by kdtalgo** [CEMPD/ctools#176]
Changing the scenario name in the 'Perform Analysis' tab also changes the names of all scenarios previously run in that port in the 'Load A Scenario -> Run' tab where you check the status of the runs.

For example:
1) Select a port, e.g. Charleston
2) Go to the Perform Analysis tab, call the run "Charleston Hourly" and submit an hourly run
3) Come back to the Perform Analysis tab, select annual and call the scenario "Charleston Annual"
4) Go to check the status of the runs in the Load a Scenario -> Run tab, it renames all previous Charleston runs "Charleston Annual", even the hourly run

**Comment by kdtalgo** [comment]
This is a major problem because you can't compare scenarios anymore. The previous scenario gets renamed to the current scenario so the Compare Scenarios tab doesn't differentiate between the 2 scenarios and won't let you run the comparison.

**Comment by cseppan** [comment]
Make sure you're copying your scenario when appropriate. For example, in your first case, after step 2, you should create a copy of the Charleston Hourly scenario, instead of modifying the existing scenario. To make things easier, I added a new button labeled "Save as a New Scenario" in the "Perform analysis" panel. If you click the "Save Changes" button, you'll save any changes to your existing scenario.

**Comment by kdtalgo** [comment]
Thanks! It makes sense with this new button.
