### ISSUE TITLE
Status: failed for raw difference analysis

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#184]
Test case was Charleston, SC; ship-in-transit sources; acrolein; annual (base case)
![c-port_charls_sitannualacrolein](https://cloud.githubusercontent.com/assets/10145737/10889789/fdc2014c-8161-11e5-9e5a-30a61041f9c0.png)

Created a 2nd scenario (new case) same as above except multiplied the ship-in-transit emissions by a factor of 100.
![c-port_charls_sitannualacroleinxmult](https://cloud.githubusercontent.com/assets/10145737/10890141/514cc2aa-8164-11e5-8116-69e13aca1dc0.png)

Created a raw difference analysis using the above base case and new case. C-PORT returned status FAILED. Why?

NOTE: Above failed on 10/26 and again when tried on 11/2.

**Comment by cseppan** [comment]
I think the concentration cutoff of 0.02 for acrolein is causing problems in raw difference mode due to the log scale and sign handling.

**Comment by cseppan** [comment]
Commit ee5e499c5b0cbf2dfbe2da9b2f3ba6205e57a10b fixes the underlying bug. Note that raw difference mode uses a log scale display. Because of this, difference values between -1 and 1 are set to zero. Since the pollutant-specific maximum value for acrolein is 0.02, all values in raw difference mode will be zero.
