### ISSUE TITLE
2 Issues after Loading a Saved Raw Difference

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#188]
Issue #1: Probe mode not available
Loaded the results of a raw difference. Differences shown were less than expected. Tried to go into "probe" mode to see actual values. Only thing shown under Visualization options was Clear overlay.

![c-port_pasc_reloadresults_cannotprobe_stuckinrds](https://cloud.githubusercontent.com/assets/10145737/10893358/5fe3b000-8176-11e5-8c7b-1cbd89e8f864.PNG)

Issue #2: Got stuck in a source type not in analysis (Clear selections button?)
When clicked on map, selected a ship-in-transit segment and that tile popped up. Selected to Clear Selections and ship-in-transit cleared but a Roads tile showed up without any roads. Could not dismiss this box because roads tile was not active.

**Comment by cseppan** [comment]
The visualization options aren't available for comparison runs yet, only base scenario runs.

In the second case, the system defaults to opening the roads panel since it has the best chance of having sources to display (i.e. most locations will have roads unless they're specifically turned off). The empty panel can be closed by selecting any of the other options or hitting the Escape button.
