### ISSUE TITLE
Scaling of results needs more work

### ISSUE THREAD

**Issue by joellenb** [CEMPD/ctools#89]
Attached is a quick test from Atlanta. Note the range in the legend.

![atlanta_test_range_02092015](https://cloud.githubusercontent.com/assets/10145737/6115064/c3b0c596-b070-11e4-81d9-b2f561af5cd2.PNG)

The actual range is very different from that shown in the legend.

![atlanta_test_concs_02092015](https://cloud.githubusercontent.com/assets/10145737/6115157/672519d4-b071-11e4-9c7c-fe1e336c2aa7.PNG)

A more intelligent range would be 1 - 10^5.

**Comment by michellegrace** [comment]
Also note there is a user had the option to change the color scales manually, as in issue #77. 

These issues are definitely related, however this issues addresses the initial range that will be displayed (then the user can modify ranges as in issue #77). This initial range should be determined intelligently, i.e. if the minimum calculated concentration is ~1, then the minimum on the scale should be 1; else, if the minimum calculated concentration is <10^-6, then the minimum should be 10^-6.

**Comment by nathan-rice** [comment]
If I use the actual min of the data rather than 10E-6, then I move the transparency from ~0 to  whatever the min of the data is, washing out the very detail you want to show.

**Comment by michellegrace** [comment]
Nathan, do you have a screenshot of this? I would like to see how much it is washing out the data. If the min is 1 or 10^0 and the max is 10^5, then 6 orders of magnitude are colored. In a traditional RGB color scheme there are 7 colors VIBGYOR; in our case, there are 8 colors because transparency is below "V"iolet. Thus these colors would be split into 5 chunks for the 6 levels of magnitude, or one order of magnitude would represent just over a full range of one color. From the screenshot of the concentration file there would at least be some color change when going from 10^0 to 10^1 to 10^2 values (this would be close to 3 colors or the whole V to B spectrum). I do not know what the other concentrations look like for this case....... 

Jo Ellen, please send me the concentration file if you have it, or re-run if you have the scenario saved. I will plot this offline in matlab, see if I can give any insight. Thanks.

**Comment by nathan-rice** [comment]
You asked for 0 to be transparent elsewhere, I implemented that because I agree that is intuitive.  Making non zero predictions transparent is not intuitive, and obscures low level data.

**Comment by arunacs** [comment]
While I like use of dynamic scales too, okay to freeze this for now, and revisit this for the May release.
